### ISSUE TITLE
Inputs / hit sounds are played at the BPM of the song at the time of placement instead of the proper song BPM setting

### ISSUE THREAD

**Issue by suprstarrd** [GDColon/URLX#2]
I'm not sure what else I can add to this. Running on Chrome 97.0.4692.102

**Comment by GDColon** [comment]
Can you record a video? Works find on my end.

**Comment by suprstarrd** [comment]
Just tried on Firefox 98.0.2 and I can reproduce. Will fiddle with OBS since for some reason today it doesn't want to let me add anything to my scenes

**Comment by suprstarrd** [comment]
I tried setting the BPM to 200 and yeah, inputs and hit sounds are at 100bpm while the rest (address bar / metronome) isn't. Autoplay handles it fine though and does inputs at 100bpm. A human player... couldn't do that probably

**Comment by suprstarrd** [comment]
I've changed the title as I've now discovered why they were "horribly off".

Here's the [.urlzip](https://cdn.discordapp.com/attachments/545387038484987925/968632528195973140/untitled.urlzip) and [.urlx](https://cdn.discordapp.com/attachments/545387038484987925/968632600711270450/untitled.urlx). My current computer's recordings suck absolute balls so I'll re-record with a video on my other computer ASAP

**Comment by jbmagination** [comment]
I've changed the title as I've now discovered why they were "horribly off".

**Comment by GDColon** [comment]
Hmm, this most likely means that the notes aren't being updated correctly. Does the issue persist after typing `game.conductor.updateActionSecs()` in the console?

**Comment by Nadwey** [comment]
I was able to reproduce this issue, and running `game.conductor.updateActionSecs()` fixed it...

https://user-images.githubusercontent.com/81181783/165526193-ab974ccc-e943-4fc4-bbf2-a1566eb09c96.mp4

**Comment by GDColon** [comment]
Aha yeah, most timings in the game are stored in seconds instead of beats (because of bpm changes, etc), I guess they just didn't update. You can even see the function failing in the video above, how convenient

**Comment by GDColon** [comment]
Fixed in latest update, I wrote `this.conductor` instead of `this.game.conductor`. Thank you for showing the error in the console!

**Comment by Nadwey** [comment]
> Fixed in latest update, I wrote `this.conductor` instead of `this.game.conductor`. Thank you for showing the error in the console!

I didn't even notice them, because brave is always showing me them lol
