### ISSUE TITLE
Loading chart fails if no notes have been placed.

### ISSUE THREAD

**Issue by Nadwey** [GDColon/URLX#7]
Video: (+ another bug? (00:10))
https://user-images.githubusercontent.com/81181783/166314224-eaaaab3c-cc48-4678-b749-45686ee11f4a.mp4

**Comment by GDColon** [comment]
Can you send the chart file?

**Comment by Nadwey** [comment]
It happens to me with any chart file (also loading from rhythm game), but sure
[[object HTMLInputElement].zip](https://github.com/GDColon/URLX/files/8606374/object.HTMLInputElement.zip)

**Comment by GDColon** [comment]
Fixed
